apiVersion: v1
kind: Service
metadata:
  name: chia-blockchain
spec:
  ports:
  - name: "8555"
    port: 8555
    targetPort: 8555
  - name: "8444"
    port: 8444
    targetPort: 8444
  selector:
    app: chia-blockchain
